### ISSUE TITLE
Avoid plagiarism

### ISSUE THREAD

**Issue by Yojahuang** [detaomega/db_HW#1]
To avoid plagiarism, you guys should turn this repo into `private`, and maybe after deadline you can turn into `public archive`.
@detaomega @austin030606

**Comment by Yojahuang** [comment]
Also you guys should consider use `.gitignore`, otherwise you will have `.DS_Store` all over your repo.

**Comment by austin030606** [comment]
Got it!
Thanks a lot for the advice.
